### ISSUE TITLE
No module named 'keras.preprocessing.text'

### ISSUE THREAD

**Issue by syr-cn** [Kohulan/Smiles-TO-iUpac-Translator#33]
Thanks for you great work.
When running the demo script in the README.md, I get the following error:
```
Traceback (most recent call last):
  File "/[my_path]/stout_demo.py", line 8, in <module>
    IUPAC_name = translate_forward(SMILES)
  File "/root/miniconda3/envs/stout/lib/python3.10/site-packages/STOUT/stout.py", line 62, in translate_forward
    inp_lang = pickle.load(
ModuleNotFoundError: No module named 'keras.preprocessing.text'
```

I try to load the `STOUT-V2/models/assets/tokenizer_input.pkl` file manually: `pickle.load(open('tokenizer_input.pkl', 'rb'))`
I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'keras.preprocessing.text'
```

Is there any problem with the pkl file? How can I solve this problem?

**Comment by syr-cn** [comment]
Build from source solved my problem. Sorry for the bothering
